---
title: "02D.2month"
author: "Elliott Schmidt"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: true  
    toc_depth: 2
    toc_float: true
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 4
    fig_width: 6
    highlight: monochrome
    theme: cerulean
    latex_engine: xelatex
---



# Load libraries

```{r load-libraries, warning=FALSE, message=FALSE}
library(tidyverse) # data manipulation
library(ggpubr) # producing data exploratory plots
library(modelsummary) # descriptive data 
library(glmmTMB) # running generalised mixed models 
library(DHARMa) # model diagnostics 
library(performance) # model diagnostics  
library(ggeffects) # partial effect plots 
library(car) # running Anova on model 
library(emmeans) # post-hoc analysis 
library(patchwork) # joining plots
```

```{r warning=FALSE}
m2 <- read_csv("import_data/2_month_size_data_2022_2023.csv") |> 
  mutate(across(1:15,factor)) |> 
  mutate(STANDARD_LENGTH=LENGTH, 
         .keep = "unused") |> 
  select(!(NOTES)) |> 
  select(1:15,"STANDARD_LENGTH","MASS")|> 
  group_by(CLUTCH_NUMBER) |> 
  mutate(DENSITY = n()) |> 
  ungroup()

m2.5 <- read_csv("import_data/2-5_month_size_data_2022_2023.csv") |> 
  mutate(across(1:15,factor)) |> 
  mutate(STANDARD_LENGTH =LENGTH, 
         .keep = "unused") |> 
  select(!(NOTES)) |> 
  select(1:15,"STANDARD_LENGTH","MASS")|> 
  group_by(CLUTCH_NUMBER) |> 
  mutate(DENSITY = n()) |> 
  ungroup()

adult <- read_csv("import_data/adult_size_2022_2023.csv") |> 
  mutate(across(1:3,factor), 
         MALE = FISH_ID, 
         FEMALE = FISH_ID, 
         POPULATION = str_sub(FISH_ID, 2,4), 
         POPULATION = case_when(POPULATION == "ARL" ~ "Arlington Reef", 
                                POPULATION == "SUD" ~ "Sudbury Reef",
                                POPULATION == "VLA" ~ "Vlassof cay",
                                POPULATION == "PRE" ~ "Pretty patches", 
                                TRUE ~ POPULATION)) |> 
  left_join(select(m2.5, c("MALE","TEMPERATURE")), 
             by="MALE") |> 
  left_join(select(m2.5, c("FEMALE","TEMPERATURE")), 
             by="FEMALE") |>
  distinct() |> 
  mutate(TEMPERATURE = coalesce(TEMPERATURE.x, TEMPERATURE.y)) |> 
  drop_na(TEMPERATURE) |> 
  select(-c("TEMPERATURE.x","TEMPERATURE.y"))
```

```{r}
m2_df_all <- m2 |> 
  left_join(select(adult, c("MALE", "SL", "MASS")), 
            by ="MALE") |> 
  mutate(SL_MALE =SL, 
         MASS_MALE =MASS.y, 
         .keep = "unused") |>
  left_join(select(adult, c("FEMALE", "SL", "MASS")), 
            by ="FEMALE") |> 
  mutate(SL_FEMALE =SL, 
         MASS_FEMALE =MASS, 
         .keep ="unused") |> 
  mutate(SL_MIDPOINT = (SL_MALE+SL_FEMALE)/2, 
         MASS_MIDPOINT = (MASS_MALE+MASS_FEMALE)/2) |> 
  rename(MASS = MASS.x) |> 
  drop_na(MASS) 
```

# Models

## Random factors
```{r}
modelNULL <- glmmTMB(MASS ~ 1, 
                  family=gaussian(),
                  data =m2_df_all)

model1 <- glmmTMB(MASS ~ (1|MALE), 
                  family=gaussian(),
                  data = m2_df_all)

AIC(modelNULL, model1) 
BIC(modelNULL, model1)
```

```{r}
model1a <- glmmTMB(MASS ~ scale(MASS_MALE, center=TRUE)*TEMPERATURE + scale(DENSITY, center=TRUE) + (1| MALE),                     
                   family=gaussian(), 
                   data=m2_df_all)

model1c <- glmmTMB(MASS ~ scale(MASS_MALE, center=FALSE)*TEMPERATURE + scale(DENSITY, center=FALSE) + (1| MALE),                     
                   family=Gamma(), 
                   data=m2_df_all)
```

## Alternative hypothesis

```{r}
model1b <- glmmTMB(MASS ~ scale(MASS_MALE, center=TRUE)*TEMPERATURE + scale(as.numeric(PARENTAL_DAYS_IN_TREATMENT), center=TRUE) + scale(DENSITY, center=TRUE) + (1| MALE),
                   family=gaussian(), 
                   data=m2_df_all)
```


## Model selection

```{r}
AIC(model1a, model1b,model1c, k=5) 
``` 


# Model validation {.tabset}

## DHARMa

```{r}
model1a |> 
  simulateResiduals(plot=TRUE)  

model1a |> testResiduals(plot=T) 
```

## performance 
```{r}
check_model(model1a) 
``` 

## {-}

# Partial effect plots

```{r warning=FALSE, message=FALSE}
model1a |> ggemmeans(~MASS_MALE|TEMPERATURE) |> 
  plot(add.data =TRUE) 

model1a |> ggemmeans(~TEMPERATURE) |> 
  plot(add.data =TRUE)  

model1a |> ggemmeans(~DENSITY) |> 
  plot(add.data =TRUE)  
```

# Model investigation {.tabset}

## Summary

```{r}
model1a |> summary()
```

## Anova

```{r}
model1a |> Anova()
```

## Confint

```{r}
model1a |> confint()
```

## r-squared

```{r}
model1a |> r2_nakagawa()
```

## {-} 

# Summary figure

```{r fig.height = 8, fig.width=12}
m2.mass <- emmeans(model1a, ~ MASS_MALE*TEMPERATURE, type="response",
                 at =list(MASS_MALE=seq(from =min(m2_df_all$MASS_MALE), to =max(m2_df_all$MASS_MALE), by=.1)))

m2.mass.df <- as.data.frame(m2.mass)

m2.mass.obs <- drop_na(m2_df_all, MASS_MALE, MASS) |> 
  mutate(Pred =predict(model1a, re.form=NA, type ='response'), 
         Resid =residuals(model1a, type ='response'), 
         Fit =Pred+Resid) 

m2.mass.obs.summarize <-  m2.mass.obs |> 
  group_by(MALE, TEMPERATURE) |> 
  summarise(mean.mass =mean(Fit, na.rm=TRUE), 
            mean.mass.male =mean(MASS_MALE, na.rm = TRUE), 
            sd.mass =sd(Fit, na.rm =TRUE), 
            n.mass = n()) |> 
  mutate(se.mass = sd.mass / sqrt(n.mass), 
         lower.ci.mass =mean.mass - qt(1-(0.05/2), n.mass -1) * se.mass, 
         upper.ci.mass =mean.mass + qt(1-(0.05/2), n.mass -1) * se.mass) |> 
  ungroup()

m2.plot <- ggplot(data = m2.mass.df, aes(x=MASS_MALE, y=emmean)) + 
  stat_smooth(aes(color=TEMPERATURE), 
              method = "lm") + 
  geom_ribbon(aes(ymin=lower.CL, ymax=upper.CL, fill=TEMPERATURE), alpha=0.5) +
  geom_pointrange(data = m2.mass.obs.summarize, aes(x =mean.mass.male, 
                                                  y =mean.mass, 
                                                  ymin =lower.ci.mass, 
                                                  ymax =upper.ci.mass, 
                                                  color = TEMPERATURE)) +  
  scale_color_manual(values = c("#69d7d8","#ff9c56", "#903146")) + 
  scale_fill_manual(values =c("#69d7d8","#ff9c56", "#903146")) +
  facet_wrap(~TEMPERATURE)+
  scale_y_continuous(limits = c(0,0.5), breaks = seq(0,0.5,by=0.05))+
  xlab("PARENTAL MASS (g)") + 
  ylab("OFFSPRING MASS (g)") + 
  ggtitle("Offspring-male relationship: 1-month offspring") +
  theme_classic()+theme(legend.position = 'none')

m2.density <- ggdensity(m2.mass.obs, x="Fit", 
          color = "TEMPERATURE", 
          fill = "TEMPERATURE", 
          rug=TRUE, 
          add="median", 
          alpha=0.5,
          palette=c("#69d7d8","#ff9c56", "#903146")) + 
  scale_x_continuous(limits = c(0,0.5), breaks = seq(0,0.5,by=0.05))+
          clean_theme() + rotate() + 
  theme(legend.position = c(0.7,0.9), 
                                legend.box.background = element_rect(color = "black", size=2))

m2.plot.final <-m2.plot + m2.density + 
  plot_layout(guides = "collect" & theme(legend.position = "bottom"), 
              widths = c(2,1)); m2.plot.final

``` 

# Slopes

```{r}
add.df <- split(m2.mass.obs.summarize, m2.mass.obs.summarize$TEMPERATURE) |> 
  map(~lm(mean.mass ~ mean.mass.male, data=.)) |> 
  map(summary) |> 
  map_dbl("r.squared") |> 
  as.data.frame()

add.df <- add.df |>
  mutate(TEMPERATURE = row.names(add.df)) |>
  rename(r.sqaured =names(add.df)[1]) 

sd_values <- m2_df_all |> group_by(TEMPERATURE) |> 
  summarise(sd =sd(MASS), 
            se =sd(MASS)/sqrt(nrow(m2_df_all)), 
            Lower.CI =mean(MASS) - qt(1-(0.05/2), nrow(m2_df_all) -1) *se, 
            Upper.CI =mean(MASS) + qt(1-(0.05/2), nrow(m2_df_all) -1) *se)  

df.results.1 <- m2.mass.obs.summarize |> 
  group_by(TEMPERATURE) |> 
  do({ 
    mod = lm(mean.mass ~ mean.mass.male, data = .) 
    data.frame(group = "1-months", 
               slope = coef(mod)[2], 
               Heritability = coef(mod)[2]*2)
    }) |> 
  as.data.frame() |> 
  mutate(Heritability = case_when(Heritability <=0 ~ 0, 
                                  TRUE ~ Heritability)) |> 
  inner_join(add.df, by="TEMPERATURE") |> 
  inner_join(sd_values, by="TEMPERATURE"); df.results.1
``` 

# Within parental variation 

```{r}
cv_within <- m2.mass.obs |> 
  group_by(MALE) |> 
  mutate(mean_value =mean(Fit), 
         sd_value =sd(Fit), 
         CV =(sd_value/mean_value) * 100) |>
  ungroup() |> 
  select(-c("SAMPLE_NO","STANDARD_LENGTH","MASS","Pred","Fit","Resid")) |> 
  distinct(MALE, .keep_all=TRUE) 

within_var <- aov(CV ~ TEMPERATURE, 
                  data=cv_within) 
summary(within_var) 
```

# Among parental variation
```{r}
cv_among <- cv_within |> 
  group_by(TEMPERATURE) |> 
  mutate(mean_among =mean(CV), 
         sd_among =sd(CV), 
         cv_among =(sd_among/mean_among)*100) |> 
  ungroup() |> 
  distinct(cv_among, .keep_all = T) |> 
  select(c("TEMPERATURE","cv_among")) |> 
  arrange(TEMPERATURE)
cv_among
```