---
title: '02A. Maternal Effects and Reproduction: Hatching success'
author: "Elliott Schmidt"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: true  
    toc_depth: 2
    toc_float: true
    code_folding: show
    collapse: no
    df_print: paged
    fig_caption: yes
    fig_height: 4
    fig_width: 6
    highlight: monochrome
    theme: cerulean
    latex_engine: xelatex
---

# Load libraries

```{r load-libraries, warning=FALSE, message=FALSE}
library(tidyverse) # data manipulation
library(ggpubr) # producing data exploratory plots
library(modelsummary) # descriptive data 
library(glmmTMB) # running generalised mixed models 
library(DHARMa) # model diagnostics 
library(performance) # model diagnostics  
library(ggeffects) # partial effect plots 
library(car) # running Anova on model 
library(emmeans) # post-hoc analysis  
library(MuMIn) # model comparisons
library(lme4)  #blups
library(patchwork) #aligning plots
``` 

# Import data

```{r message=FALSE, warning=FALSE}
setwd("C:/Users/elliott/OneDrive/jc527762/PhD dissertation/Data/Chapter3_Heritability_ARCHIVED")
egg <- read_csv("import_data/egg_size_data_2022_2023.csv") |> 
  mutate(across(1:14,factor))  |> 
  select(!c(NOTES,...18, IMAGE))   

reprod.data <- read_csv("import_data/clutch_data_2022_2023.csv") |> 
  mutate(across(c(1:7,16,23), factor))  
  

m2.5 <- read_csv("import_data/2-5_month_size_data_2022_2023.csv") |> 
  mutate(across(1:15,factor)) |> 
  mutate(STANDARD_LENGTH =LENGTH, 
         .keep = "unused") |> 
  select(!(NOTES)) |> 
  select(1:15,"STANDARD_LENGTH","MASS")|> 
  group_by(CLUTCH_NUMBER) |> 
  mutate(DENSITY = n()) |> 
  ungroup()

adult <- read_csv("import_data/adult_size_2022_2023.csv") |> 
  mutate(across(1:3,factor), 
         MALE = FISH_ID, 
         FEMALE = FISH_ID, 
         POPULATION = str_sub(FISH_ID, 2,4), 
         POPULATION = case_when(POPULATION == "ARL" ~ "Arlington Reef", 
                                POPULATION == "SUD" ~ "Sudbury Reef",
                                POPULATION == "VLA" ~ "Vlassof cay",
                                POPULATION == "PRE" ~ "Pretty patches", 
                                TRUE ~ POPULATION)) |> 
  left_join(select(m2.5, c("MALE","TEMPERATURE")), 
             by="MALE") |> 
  left_join(select(m2.5, c("FEMALE","TEMPERATURE")), 
             by="FEMALE") |>
  distinct() |> 
  mutate(TEMPERATURE = coalesce(TEMPERATURE.x, TEMPERATURE.y)) |> 
  drop_na(TEMPERATURE) |> 
  select(-c("TEMPERATURE.x","TEMPERATURE.y")) 
```

# Data manipulation

```{r}
m2.5_df_all <- m2.5 |> 
  left_join(select(adult, c("MALE", "SL", "MASS")), 
            by ="MALE") |> 
  mutate(SL_MALE =SL, 
         MASS_MALE =MASS.y, 
         .keep = "unused") |>
  left_join(select(adult, c("FEMALE", "SL", "MASS")), 
            by ="FEMALE") |> 
  mutate(SL_FEMALE =SL, 
         MASS_FEMALE =MASS, 
         .keep ="unused") |> 
  mutate(SL_MIDPOINT = (SL_MALE+SL_FEMALE)/2, 
         MASS_MIDPOINT = (MASS_MALE+MASS_FEMALE)/2) 

m2.5_df <- m2.5_df_all |>
  group_by(CLUTCH_NUMBER) |> 
  mutate(MEDIAN_STANDARD_LENGTH = median(STANDARD_LENGTH)) |>
  drop_na(MEDIAN_STANDARD_LENGTH) |>
  ungroup() |> 
  select(-c("STANDARD_LENGTH","MASS.x")) |> 
  distinct() |> 
  mutate(MASS_MIDPOINT =coalesce(MASS_MIDPOINT, MASS_MALE), 
         SL_MIDPOINT =coalesce(SL_MIDPOINT, SL_MALE)) 

clutches <- reprod.data |> filter(PROJECT_CODE %in% c("1","3","5","7")) |>
  select(CLUTCH_NUMBER)

egg_df_all <- egg |> 
  left_join(select(adult, c("MALE", "SL", "MASS")), 
            by ="MALE")  |> 
  mutate(SL_MALE =SL, 
         MASS_MALE =MASS, 
         .keep = "unused") |>
  left_join(select(adult, c("FEMALE", "SL", "MASS")), 
            by ="FEMALE") |> 
  mutate(SL_FEMALE =SL, 
         MASS_FEMALE =MASS, 
         .keep ="unused") |> 
  mutate(SL_MIDPOINT = (SL_MALE+SL_FEMALE)/2, 
         MASS_MIDPOINT = (MASS_MALE+MASS_FEMALE)/2) |> 
  left_join(select(reprod.data, c("CLUTCH_NUMBER","EGG_COUNT","HATCHING_SUCCESS")), by="CLUTCH_NUMBER")

egg_df <- egg_df_all |>
  group_by(CLUTCH_NUMBER) |> 
  mutate(MEDIAN_HATCHING_SUCCESS = median(HATCHING_SUCCESS), 
         MEDIAN_EGG_SIZE = median(EGG_SIZE)) |> 
  drop_na(MEDIAN_HATCHING_SUCCESS) |>
  ungroup()  |> 
  select(-c("EGG_SIZE","SAMPLE")) |> 
  distinct() |> 
  mutate(MASS_MIDPOINT =coalesce(MASS_MIDPOINT, MASS_MALE), 
         SL_MIDPOINT =coalesce(SL_MIDPOINT, SL_MALE), 
         SL_FEMALE =coalesce(SL_FEMALE, SL_MALE))  # done for two individuals

egg_df <- clutches |> 
  inner_join(egg_df, by="CLUTCH_NUMBER") |> 
  drop_na(HATCHING_SUCCESS) |> 
  droplevels()
```

# Exploratory data analysis 

```{r fig.width=12, fig.height=6, warning=FALSE, message=FALSE}
plot1 <- ggplot(egg_df, aes(x=MASS_FEMALE, y=HATCHING_SUCCESS, color=TEMPERATURE)) +
  geom_point(alpha=0.05) + 
  stat_smooth(method = "lm", se=FALSE) +
  scale_color_manual(values = c("#69d7d8","#ff9c56", "#903146")) + 
  ggtitle("HATCHING SUCCESS") +
  theme_classic(); plot1
```

# Descriptive statistics 

```{r}
datasummary(Factor(POPULATION) ~ Factor(TEMPERATURE), 
            data=egg_df, 
            fmt = "%.0f") 
```

```{r}
datasummary(Factor(TEMPERATURE) ~ HATCHING_SUCCESS * (NUnique + mean + median + min + max + sd + Histogram), 
            data = drop_na(egg_df),  
            fmt = "%.2f")
```  

```{r}
sample_size_hatchsuccess <- egg_df |> 
  group_by(TEMPERATURE, MALE, FEMALE, POPULATION, CLUTCH_NUMBER, HATCHING_SUCCESS) |> 
  summarise(n =n(), .groups = "drop"); sample_size_hatchsuccess

write.csv(sample_size_hatchsuccess, "../../sample_size_hatchsuccess.csv")
```


# Fit models [random factors] 

```{r}
modelNULL <- glmmTMB(HATCHING_SUCCESS ~ 1, 
                  family=gaussian(),
                  data =egg_df)

model1 <- glmmTMB(HATCHING_SUCCESS ~ (1|FEMALE), 
                  family=gaussian(),
                  data = egg_df)

AIC(modelNULL, model1, k=2) 
BIC(modelNULL, model1)
```

# Fit fixed factors

## Main hypothesis

```{r}
model1a <- glmmTMB(HATCHING_SUCCESS ~ TEMPERATURE + scale(MASS_FEMALE, center=TRUE) + (1|FEMALE), 
                    family=beta_family(), 
                    data=egg_df)
```

## Alternative hypothesis

```{r}
model1b <- glmmTMB(HATCHING_SUCCESS ~ TEMPERATURE + scale(MASS_FEMALE, center=TRUE) + scale(as.numeric(DAYS_IN_TREATMENT), center=TRUE) + scale(MEDIAN_EGG_SIZE, center=TRUE) +  (1|FEMALE), 
                    family=beta_family(), 
                    data=egg_df)

model1c <- glmmTMB(HATCHING_SUCCESS ~ TEMPERATURE * scale(MASS_FEMALE, center=TRUE) +  (1|FEMALE), 
                    family=beta_family(), 
                    data=egg_df)
```

## Model selection

```{r}
AICc(model1a, model1b, model1c, k=5) 
```

# Model validation {.tabset}

## DHARMa

```{r}
model1a |> 
  simulateResiduals(plot=TRUE)  

model1a |> testResiduals(plot=T) 
``` 

## {-}

# Partial effect plots

```{r}
model1a |> ggemmeans(~MASS_FEMALE) |> 
  plot() 

model1a |> ggemmeans(~TEMPERATURE) |> 
  plot()
``` 

# Model investigation {.tabset}

## Summary

```{r}
model1a |> summary()
```

## Anova

```{r}
model1a |> Anova()
```

## Confint

```{r}
model1a |> confint()
```

## r-squared

```{r}
model1a |> r2_nakagawa()
```
# Post-hoc 

```{r}
model1a |> emmeans(~TEMPERATURE, type ="response")
model1a |> emmeans(~TEMPERATURE, type ="response") |> pairs() |> summary() 
```

## {-}   

# Summary figure 

```{r warning=FALSE}
egg_df <- egg_df |> drop_na(HATCHING_SUCCESS, MASS_FEMALE)
egg.emm <- emmeans(model1a, ~ MASS_FEMALE*TEMPERATURE, 
                 at =list(MASS_FEMALE=seq(from =min(egg_df$MASS_FEMALE), to =max(egg_df$MASS_FEMALE), by=.25)))

hs.df <- as.data.frame(egg.emm)

hs.obs <- egg_df |> 
  mutate(Pred =predict(model1a, re.form=NULL, type ='response'), 
         Resid =residuals(model1a, type ='response'), 
         Fit =Pred+Resid) 

hs.obs.summarize <-  hs.obs |> 
  group_by(FEMALE, TEMPERATURE) |> 
  summarise(mean.hs =mean(Fit, na.rm=TRUE), 
            mean.mass.female =mean(MASS_FEMALE, na.rm = TRUE), 
            min.hs =min(Fit, na.rm=TRUE), 
            max.hs =max(Fit, na.rm=TRUE),
            sd.hs =sd(Fit, na.rm =TRUE), 
            n.hs = n()) |> 
  mutate(se.hs = sd.hs / sqrt(n.hs), 
         lower.ci.hs =mean.hs - qt(1-(0.05/2), n.hs -1) * se.hs, 
         upper.ci.hs =mean.hs + qt(1-(0.05/2), n.hs -1) * se.hs)|> 
  ungroup()

hs.obs.summarize2 <- hs.obs.summarize |> 
  group_by(TEMPERATURE) |> 
  mutate(temp_mean =mean(mean.hs), 
         temp_sd =sd(mean.hs)) |> 
  distinct(temp_mean, .keep_all = TRUE) 

mod = lm(mean.hs ~ TEMPERATURE,  
         data =hs.obs.summarize)

mod.mass <- emmeans(mod, ~ TEMPERATURE, 
                 at =list(mean.mass.female=seq(from =min(hs.obs.summarize$mean.mass.female), to =max(hs.obs.summarize$mean.mass.female), by=.01))) |> as.data.frame()

hs.plot2 <- ggplot(hs.obs.summarize, aes(x=TEMPERATURE, y=mean.hs, color=TEMPERATURE)) + 
  geom_pointrange(data=hs.obs.summarize2, 
                  aes(x=TEMPERATURE, 
                      y=temp_mean, 
                      ymin=temp_mean - temp_sd, 
                      ymax=temp_mean + temp_sd), 
                  size = 1) + 
  geom_jitter(width=0.05, 
              alpha=0.3) +  
  scale_color_manual(values = c("#69d7d8","#ff9c56", "#903146")) + 
  scale_fill_manual(values =c("#69d7d8","#ff9c56", "#903146")) +
  scale_y_continuous(limits = c(0,1.5), breaks=seq(0, 1.5, .1))+
  theme_classic() + 
  ylab("") + 
  theme(legend.position = c(0.8,0.9), 
                                legend.box.background = element_rect(color = "black", size=2)); hs.plot2
```

